[semantic_release]
assets = ["README.md", "LICENSE"]
commit_parser = "conventional"

[semantic_release.changelog]
exclude_commit_patterns = [
  '''chore(?:\([^)]*?\))?: .+''',
  '''ci(?:\([^)]*?\))?: .+''',
  '''refactor(?:\([^)]*?\))?: .+''',
  '''style(?:\([^)]*?\))?: .+''',
  '''test(?:\([^)]*?\))?: .+''',
  '''build\((?!deps\): .+)''',
  '''Merged? .*''',
  '''Initial Commit.*''',
]

[semantic_release.branches.main]
match = "^main$"
prerelease = false

[semantic_release.remote]
type = "github"
token = { env = "GH_TOKEN" }
